fragment image on UploadFileEntity {
  id
  attributes {
    alternativeText
    url
  }
}
fragment cover on UploadFileEntity {
	...image
}
fragment tag on TagEntity {
  id
  attributes {
    displayName
    slug
  }
}
fragment author on AuthorEntity {
  id
  attributes {
    displayName
    slug
  }
}
fragment category on CategoryEntity {
  id
  attributes {
    displayName
    slug
  }
}
fragment authorPost on AuthorEntity {
  ...author
}
fragment categories on CategoryEntity {
  ...category
}
fragment menuLink on ComponentMenuMenuLink {
  id
  link
  text
  newTab
}
fragment posts on PostEntity {
  id
  attributes {
    title
    slug
    excerpt
    content
    allowComments
    cover {
      data {
        ...cover
      }
    }
    categories {
      data {
        ...categories
      }
    }
    tags {
      data{
        ...tag
      }
    }
    author{
      data{
        ...authorPost
      }
    }
  }
}

fragment setting on SettingEntity {
  id
  attributes {
    blogName
    blogDescription
    logo {
      data {
        ...image
      }
    }
    menuLink {
      ...menuLink
    }
    text
  }
}

query GET_POST_BY_SLUG($slugPost: String!) {
  setting {
    data {
      ...setting
    }
  }
  posts(filters:{
    slug:{eq:$slugPost}
  }) {
    data {
      ...posts
    }
  }
}
query GET_POSTS {
  setting {
    data {
      ...setting
    }
  }
  posts {
    data {
      ...posts
    }
  }
}
query GET_POST_BY_AUTHOR($slugAuthor: String!) {
    setting {
    data {
      ...setting
    }
  }
  posts(filters: { author: { slug: { eq: $slugAuthor } } }) {
    data {
      ...posts
    }
  }
}
query GET_POST_BY_CATEGORY($slugCategory: String!) {
    setting {
    data {
      ...setting
    }
  }
  posts(filters: { categories: { slug: { eq: $slugCategory } } }) {
    data {
      ...posts
    }
  }
}
query GET_POST_BY_TAGS($slugTags: String!) {
    setting {
    data {
      ...setting
    }
  }
  posts(filters: { tags: { slug: { eq: $slugTags } } }) {
    data {
      ...posts
    }
  }
}

# Query Variables examples
{
  "slugPost": "receitinha",
  "slugAuthor": "marcus-barcelos",
  "slugCategory": "python",
  "slugTags": "use-effect"
}
